name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Setup Testcontainers Cloud
        uses: atomicjar/testcontainers-cloud-setup-action@main
        with:
          token: ${{ secrets.TCC_SECRET_EXAMPLES }}
          # Note: You must add this secret in your GitHub repository settings
          # from your Testcontainers Cloud account
      - name: Run tests
        run: ./mvnw verify
